
document.write('<div class="topbody2_div2" id="HDbar1">');
document.write('<a href="cata/thCata_103.html" class="" >手机数码</a><a href="cata/thCata_101.html" class="" >整机/外设</a><a href="cata/thCata_102.html" class="yellows" ><b>配件</b></a><a href="cata/thCata_109.html" class="" >个护健康</a><a href="cata/thCata_104.html" class="" >车载出行</a><a href="cata/thCata_105.html" class="" >钟表箱包</a><a href="cata/thCata_108.html" class="" >穿戴配饰</a><a href="cata/thCata_106.html" class="" >日用家居</a><a href="cata/thCata_107.html" class="" >文体办公</a><a href="cata/thCata_112.html" class="" >茶酒食品</a><a href="cata/thCata_113.html" class="" style="border:none;">券卡门票</a>');
document.write('</div>');
document.write('<div class="page">');
document.write('<div class="topbody2_div3"  id="HDbar2" style="display:none">');
document.write('<a href="javascript:void(0)" id="my_cart1" onMouseOver="brand_player(\'brand1\')" onMouseOut="brand_clocer(\'brand1\');" style="color:#333;">整机外设/手机数码/配件</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0)" id="my_cart2" onMouseOver="brand_player(\'brand2\')" onMouseOut="brand_clocer(\'brand2\');" style="color:#333;">康体防护/日用家居</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0)" id="my_cart3" onMouseOver="brand_player(\'brand3\')" onMouseOut="brand_clocer(\'brand3\');" style="color:#333;">钟表配饰</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0)" id="my_cart4" onMouseOver="brand_player(\'brand4\')" onMouseOut="brand_clocer(\'brand4\');" style="color:#333;">车载户外</a>');
document.write('</div>');
document.write('<div class="fubrand_body" id="brand1" OnMouseOver="brand_player(\'brand1\');" onMouseOut="brand_clocer(\'brand1\');" style="display:none;"><div class="fubrand_top"></div><div class="fubrand_center"><ul><li> <a href="brand.php?brandid=8" target="">Think</a></li><li> <a href="brand.php?brandid=151" target="">惠普</a></li><li> <a href="brand.php?brandid=126" target="">捷波朗</a></li><li> <a href="brand.php?brandid=14" target="">飞利浦</a></li><li> <a href="brand.php?brandid=2" target="">贝尔金</a></li><li> <a href="brand.php?brandid=54" target="">泰格斯</a></li><li> <a href="brand.php?brandid=685" target="">KI</a></li><li> <a href="brand.php?brandid=502" target="">IBACKS</a></li></ul></div><div class="fubrand_bottom"></div></div><div class="fubrand_body" id="brand2" OnMouseOver="brand_player(\'brand2\');" onMouseOut="brand_clocer(\'brand2\');" style="display:none;"><div class="fubrand_top"></div><div class="fubrand_center"><ul><li> <a href="brand.php?brandid=3" target="">3M</a></li><li> <a href="brand.php?brandid=10" target="">欧姆龙</a></li><li> <a href="brand.php?brandid=140" target="">美的</a></li><li> <a href="brand.php?brandid=189" target="">荣事达</a></li><li> <a href="brand.php?brandid=87" target="">德龙</a></li><li> <a href="brand.php?brandid=65" target="">双立人</a></li><li> <a href="brand.php?brandid=158" target="">依铂雷司</a></li><li> <a href="brand.php?brandid=679" target="">一水间</a></li><li> <a href="brand.php?brandid=691" target="">Artiart</a></li></ul></div><div class="fubrand_bottom"></div></div><div class="fubrand_body" id="brand3" OnMouseOver="brand_player(\'brand3\');" onMouseOut="brand_clocer(\'brand3\');" style="display:none;"><div class="fubrand_top"></div><div class="fubrand_center"><ul><li> <a href="brand.php?brandid=212" target="">天梭</a></li><li> <a href="brand.php?brandid=211" target="">美度</a></li><li> <a href="brand.php?brandid=467" target="">施华洛世奇</a></li><li> <a href="brand.php?brandid=209" target="">金世玉</a></li><li> <a href="brand.php?brandid=210" target="">德增玉坊</a></li></ul></div><div class="fubrand_bottom"></div></div><div class="fubrand_body" id="brand4" OnMouseOver="brand_player(\'brand4\');" onMouseOut="brand_clocer(\'brand4\');" style="display:none;"><div class="fubrand_top"></div><div class="fubrand_center"><ul><li> <a href="brand.php?brandid=19" target="">探路者</a></li><li> <a href="brand.php?brandid=11" target="">Swiss</a></li></ul></div><div class="fubrand_bottom"></div></div>');
document.write('</div>');


