document.write('<div class="topbody2_div2" id="HDbar1">');
document.write('<a href="cata/thCata_103.html" class="" >�ֻ�����</a><a href="cata/thCata_101.html" class="" >����/����</a><a href="cata/thCata_102.html" class="yellows" ><b>���</b></a><a href="cata/thCata_109.html" class="" >��������</a><a href="cata/thCata_104.html" class="" >���س���</a><a href="cata/thCata_105.html" class="" >�ӱ����</a><a href="cata/thCata_108.html" class="" >��������</a><a href="cata/thCata_106.html" class="" >���üҾ�</a><a href="cata/thCata_107.html" class="" >����칫</a><a href="cata/thCata_112.html" class="" >���ʳƷ</a><a href="cata/thCata_113.html" class="" style="border:none;">ȯ����Ʊ</a>');
document.write('</div>');
document.write('<div class="page">');
document.write('<div class="topbody2_div3"  id="HDbar2" style="display:none">');
document.write('<a href="javascript:void(0)" id="my_cart1" onMouseOver="brand_player(\'brand1\')" onMouseOut="brand_clocer(\'brand1\');" style="color:#333;">��������/�ֻ�����/���</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0)" id="my_cart2" onMouseOver="brand_player(\'brand2\')" onMouseOut="brand_clocer(\'brand2\');" style="color:#333;">�������/���üҾ�</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0)" id="my_cart3" onMouseOver="brand_player(\'brand3\')" onMouseOut="brand_clocer(\'brand3\');" style="color:#333;">�ӱ�����</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0)" id="my_cart4" onMouseOver="brand_player(\'brand4\')" onMouseOut="brand_clocer(\'brand4\');" style="color:#333;">���ػ���</a>');
document.write('</div>');
document.write('<div class="fubrand_body" id="brand1" OnMouseOver="brand_player(\'brand1\');" onMouseOut="brand_clocer(\'brand1\');" style="display:none;"><div class="fubrand_top"></div><div class="fubrand_center"><ul><li> <a href="brand.php?brandid=8" target="">Think</a></li><li> <a href="brand.php?brandid=151" target="">����</a></li><li> <a href="brand.php?brandid=126" target="">�ݲ���</a></li><li> <a href="brand.php?brandid=14" target="">������</a></li><li> <a href="brand.php?brandid=2" target="">������</a></li><li> <a href="brand.php?brandid=54" target="">̩��˹</a></li><li> <a href="brand.php?brandid=685" target="">KI</a></li><li> <a href="brand.php?brandid=502" target="">IBACKS</a></li></ul></div><div class="fubrand_bottom"></div></div><div class="fubrand_body" id="brand2" OnMouseOver="brand_player(\'brand2\');" onMouseOut="brand_clocer(\'brand2\');" style="display:none;"><div class="fubrand_top"></div><div class="fubrand_center"><ul><li> <a href="brand.php?brandid=3" target="">3M</a></li><li> <a href="brand.php?brandid=10" target="">ŷķ��</a></li><li> <a href="brand.php?brandid=140" target="">����</a></li><li> <a href="brand.php?brandid=189" target="">���´�</a></li><li> <a href="brand.php?brandid=87" target="">����</a></li><li> <a href="brand.php?brandid=65" target="">˫����</a></li><li> <a href="brand.php?brandid=158" target="">������˾</a></li><li> <a href="brand.php?brandid=679" target="">һˮ��</a></li><li> <a href="brand.php?brandid=691" target="">Artiart</a></li></ul></div><div class="fubrand_bottom"></div></div><div class="fubrand_body" id="brand3" OnMouseOver="brand_player(\'brand3\');" onMouseOut="brand_clocer(\'brand3\');" style="display:none;"><div class="fubrand_top"></div><div class="fubrand_center"><ul><li> <a href="brand.php?brandid=212" target="">����</a></li><li> <a href="brand.php?brandid=211" target="">����</a></li><li> <a href="brand.php?brandid=467" target="">ʩ��������</a></li><li> <a href="brand.php?brandid=209" target="">������</a></li><li> <a href="brand.php?brandid=210" target="">������</a></li></ul></div><div class="fubrand_bottom"></div></div><div class="fubrand_body" id="brand4" OnMouseOver="brand_player(\'brand4\');" onMouseOut="brand_clocer(\'brand4\');" style="display:none;"><div class="fubrand_top"></div><div class="fubrand_center"><ul><li> <a href="brand.php?brandid=19" target="">̽·��</a></li><li> <a href="brand.php?brandid=11" target="">Swiss</a></li></ul></div><div class="fubrand_bottom"></div></div>');
document.write('</div>');


